version: '3'
services:
  postgres:
    image: postgres
    container_name: 'local_postgres'
    environment:
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
